hpc_path: /fs1/home/zhq/data

Target_path: ${environment.hpc_path}/Fusion_data/CMPA/CMPA5_V3_nc/HOR/NRT_0.05_15-60_70-140_UTC_rain

EC_path:
  rain: ${environment.hpc_path}/NWP_data/EC/EC_V3_nc/ecmwf_nc_0.05_31-45_108-124_rain
  surface: ${environment.hpc_path}/NWP_data/EC/EC_V3_nc/ecmwf_nc_0.05_31-45_108-124
  pressure: ${environment.hpc_path}/NWP_data/EC/EC_V3_nc/ecmwf_nc_0.05_31-45_108-124

SMS_path:
  rain: ${environment.hpc_path}/NWP_data/SMS/SMS_V3_nc/SMS_nc_0.05_31-45_108-124_rain
  surface: ${environment.hpc_path}/NWP_data/SMS/SMS_V3_nc/SMS_nc_0.05_31-45_108-124
  pressure: ${environment.hpc_path}/NWP_data/SMS/SMS_V3_nc/SMS_nc_0.05_31-45_108-124

GRAPES_path:
  rain: ${environment.hpc_path}/NWP_data/GRAPES/GRAPES_V3_nc/GRAPES_nc_0.05_31-45_108-124_rain
  surface: ${environment.hpc_path}/NWP_data/GRAPES/GRAPES_V3_nc/GRAPES_nc_0.05_31-45_108-124

META_path: ${environment.hpc_path}/geo_data/topography_15-55_70-135_0.05.nc

index_root: /fs1/home/zhq/users/fzl/data/dataloader_v1